require: rubocop-rspec

Style/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

LineLength:
  Max: 99

Style/SafeNavigation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

AllCops:
  Exclude:
    - 'app/authentication/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'

  TargetRubyVersion: 2.3
